# Generated by Django 5.2.5 on 2026-07-21 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('funcao', models.CharField(max_length=150)),
                ('local_trabalho', models.CharField(max_length=150)),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=30, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=30, null=True)),
                ('conta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('salario_fixo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('secretaria', models.CharField(choices=[('administracao', 'Administração e Finanças'), ('assistencia', 'Assistência Social'), ('agricultura', 'Agricultura'), ('educacao', 'Educação'), ('infraestrutura', 'Infraestrutura'), ('saude', 'Saúde')], db_index=True, max_length=30)),
                ('modalidade', models.CharField(choices=[('credenciamento', 'Credenciamento'), ('prestacao', 'Prestação de Serviço')], db_index=True, max_length=30)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('demitido', 'Demitido')], db_index=True, default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['secretaria', 'modalidade'], name='funcionario_secreta_db794d_idx'), models.Index(fields=['situacao', 'secretaria'], name='funcionario_situaca_8b674d_idx')],
            },
        ),
    ]
