# Generated by Django 5.2.5 on 2026-05-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('localidade', models.CharField(blank=True, max_length=150, null=True)),
                ('escola', models.CharField(max_length=150)),
                ('carga_horaria', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('demitido', 'Demitido')], default='ativo', max_length=20)),
                ('data_admissao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Hora Extra Normal'), ('f1', 'Hora Extra F1'), ('f2', 'Hora Extra F2')], default='normal', max_length=20)),
                ('quantidade_horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mes_referencia', models.IntegerField(default=1)),
                ('ano', models.IntegerField(default=2026)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
