# Generated by Django 5.2.5 on 2026-05-13 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='telefone',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='localidade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='carga_horaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_vinculo',
            field=models.CharField(choices=[('contratado', 'Contratado'), ('concursado', 'Concursado')], default='contratado', max_length=20),
        ),
    ]
