# Generated by Django 5.2.5 on 2026-05-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_rename_telefone_funcionario_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaextra',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='valor',
        ),
        migrations.AddField(
            model_name='horaextra',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='quantidade_horas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Hora Extra Normal'), ('f1', 'Hora Extra F1'), ('f2', 'Hora Extra F2')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='valor_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('demitido', 'Demitido')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='horaextra',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
