# Generated by Django 5.2.5 on 2026-05-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_remove_horaextra_horas_remove_horaextra_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='ano_referencia',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='mes_referencia',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1),
        ),
    ]
