# Generated by Django 5.2.5 on 2026-05-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_create_admin'),
        ('funcionarios', '0003_alter_horaextra_mes_referencia_perfil'),
    ]

    operations = [
    ]
