# Generated by Django 5.2.5 on 2026-05-23 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_merge_20260522_0754'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaextra',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Hora Extra Normal'), ('f1', 'Hora Extra F1'), ('f2', 'Hora Extra F2'), ('falta', 'Falta')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
