# Generated by Django 5.2.5 on 2026-05-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_horaextra_ano_referencia_horaextra_mes_referencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horaextra',
            old_name='valor_adicional',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='ano_referencia',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='data',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='valor_hora',
        ),
    ]
