# Generated by Django 5.2.5 on 2026-05-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_rename_valor_adicional_horaextra_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='ano',
            field=models.IntegerField(default=2026),
        ),
    ]
