# Generated by Django 5.2.5 on 2026-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_horaextra_tipo_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='cor_texto',
            field=models.CharField(choices=[('normal', 'Normal'), ('vermelho', 'Vermelho'), ('verde', 'Verde')], default='normal', max_length=20),
        ),
    ]
