# Generated by Django 5.2.5 on 2026-05-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_horaextra_cor_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horaextra',
            old_name='observacao',
            new_name='observacao_hora_extra',
        ),
        migrations.AddField(
            model_name='horaextra',
            name='observacao_falta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
