# Generated by Django 5.2.5 on 2026-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_rename_observacao_horaextra_observacao_hora_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='numero_faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='horaextra',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Hora Extra Normal'), ('f1', 'Hora Extra F1'), ('f2', 'Hora Extra F2')], default='normal', max_length=20),
        ),
    ]
