# Generated by Django 5.2.5 on 2026-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_horaextra_numero_faltas_alter_horaextra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='data_falta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
