# Generated by Django 5.2.5 on 2026-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_horaextra_data_falta'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='situacao_contratual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
