# Generated by Django 5.2.5 on 2026-06-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_funcionario_situacao_contratual'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horaextra',
            unique_together={('funcionario', 'mes_referencia', 'ano')},
        ),
    ]
