# Generated by Django 5.2.5 on 2026-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_horaextra_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='encerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horaextra',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Hora Extra'), ('f1', 'Hora Aula F1'), ('f2', 'Hora Aula F2')], default='normal', max_length=20),
        ),
    ]
